"""refactor_chat_sessions

Revision ID: 69bf9aa77b01
Revises: c3f2d250811b
Create Date: 2026-06-04 23:11:52.973198+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69bf9aa77b01'
down_revision: Union[str, None] = 'c3f2d250811b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.execute("UPDATE chat_sessions SET conversation_id = id")
    op.alter_column('chat_sessions', 'conversation_id', nullable=False)
    op.create_index(op.f('ix_chat_sessions_conversation_id'), 'chat_sessions', ['conversation_id'], unique=True)
    op.create_foreign_key(None, 'chat_sessions', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.add_column('chat_summaries', sa.Column('last_summary_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_summaries', 'last_summary_at')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_conversation_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'conversation_id')
    # ### end Alembic commands ###
